name: Beta Deployment

on:
  push:
    tags:
      - '*-beta*'

jobs:
  beta-deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete previous beta release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/beta" \
            | jq -r '.id')

          if [ "$RELEASE_ID" != "null" ]; then
            curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID"
            echo "Deleted 'beta' release."
          else
            echo "Could not delete 'beta' release."
          fi

      - name: Delete previous beta tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_SHA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/git/ref/tags/beta" \
            | jq -r '.object.sha')

          if [ "$TAG_SHA" != "null" ]; then
            curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/git/refs/tags/beta"
            echo "Deleted 'beta' tag."
          else
            echo "Could not delete 'beta' tag."
          fi

      - name: Create new beta tag
        run: |
          git tag beta
          git push origin beta

      - name: Extract '-beta' tag name
        id: tag
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create new beta release
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_BODY=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.TAG_NAME }}" \
          | jq -r '.body')

          JSON_PAYLOAD=$(jq -n \
          --arg body "$RELEASE_BODY" \
          '{
            "tag_name": "beta",
            "name": "beta",
            "body": $body,
            "prerelease": true
          }')

          curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "$JSON_PAYLOAD"